### ISSUE TITLE
Implement proxy installation

### ISSUE THREAD

**Issue by stdevel** [stdevel/ansible-uyuni#2]
It would be handy to have the possibility to implement a proxy installation

**Comment by stdevel** [comment]
Investigating in branch `feat-proxy-2`

**Comment by stdevel** [comment]
# TODOs

## Staging
- [ ] install different package pattern

## Registration
- [ ] create proxy OS channel and Uyuni/SUSE Manager proxy channels
- [ ] create OS Salt bootstrap repositories
- [ ] create activation key for OS + Proxy channels
- [ ] modify bootstrap script to contain organization GPG key
- [ ] bootstrap proxy
- [ ] copy SSL certificates and run `configure-proxy.sh` (*see also [official documentation](https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-proxy-setup.html)*)

**Comment by stdevel** [comment]
This also required setting different modules, see: https://documentation.suse.com/suma/4.3/en/suse-manager/installation-and-upgrade/install-proxy-unified.html

The pattern also differs: https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/install-proxy-uyuni.html

**Comment by stdevel** [comment]
This might become part of the [Uyuni Ansible collection](https://github.com/stdevel/ansible-collection-uyuni).
